name: 'Setting context for Kubernetes cluster of Alibaba Cloud Kubernetes Service (ACK)'
description: 'Setting context for Kubernetes cluster of Alibaba Cloud Kubernetes Service (ACK)'
inputs: 
  access-key-id:
    description: 'Access key id for Alibaba Cloud'
    required: true
  access-key-secret:
    description: 'Access key secret for Alibaba Cloud'
    required: true
  security-token:
    description: 'STS token for Alibaba Cloud'
    default: ''
    required: false
  cluster-id:
    description: 'Kubernetes cluster id'
    required: true
branding:
  color: 'orange'
  icon: 'compass'
runs:
  using: 'node16'
  main: 'dist/index.js'
